# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QSpinBox



class Ui_addObj(object):
    def setupUi(self, addObj):
        addObj.setObjectName("addObj")
        addObj.resize(393, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(addObj)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(addObj)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.lineEdit = QtWidgets.QLineEdit(addObj)
        self.lineEdit.textChanged.connect(self.validateFields)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.timeLabel = QtWidgets.QLabel(addObj)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.timeLabel)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(addObj)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.coursseLabel = QtWidgets.QLabel(addObj)
        self.coursseLabel.setObjectName("coursseLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.coursseLabel)
        self.lineEdit_3 = QSpinBox()
        self.lineEdit_3.setMaximum(360)
        self.lineEdit_3.setMinimum(1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.speedLabel = QtWidgets.QLabel(addObj)
        self.speedLabel.setObjectName("speedLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.speedLabel)
        self.lineEdit_4 = QtWidgets.QLineEdit(addObj)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.symbolLabel = QtWidgets.QLabel(addObj)
        self.symbolLabel.setObjectName("symbolLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.symbolLabel)
        self.lineEdit_5 = QtWidgets.QLineEdit(addObj)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.srccallLabel = QtWidgets.QLabel(addObj)
        self.srccallLabel.setObjectName("srccallLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.srccallLabel)
        self.lineEdit_6 = QtWidgets.QLineEdit(addObj)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.dstcallLabel = QtWidgets.QLabel(addObj)
        self.dstcallLabel.setObjectName("dstcallLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.dstcallLabel)
        self.lineEdit_7 = QtWidgets.QLineEdit(addObj)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.commentLabel = QtWidgets.QLabel(addObj)
        self.commentLabel.setObjectName("commentLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.commentLabel)
        self.lineEdit_8 = QtWidgets.QLineEdit(addObj)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.pathLabel = QtWidgets.QLabel(addObj)
        self.pathLabel.setObjectName("pathLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.pathLabel)
        self.lineEdit_9 = QtWidgets.QLineEdit(addObj)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.latitudeLabel = QtWidgets.QLabel(addObj)
        self.latitudeLabel.setObjectName("latitudeLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.latitudeLabel)
        self.lineEdit_10 = QtWidgets.QLineEdit(addObj)
        self.lineEdit_10.textChanged.connect(self.validateFields)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.longitudeLabel = QtWidgets.QLabel(addObj)
        self.longitudeLabel.setObjectName("longitudeLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.longitudeLabel)
        self.lineEdit_11 = QtWidgets.QLineEdit(addObj)
        self.lineEdit_11.textChanged.connect(self.validateFields)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.elevationLabel = QtWidgets.QLabel(addObj)
        self.elevationLabel.setObjectName("elevationLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.elevationLabel)
        self.lineEdit_12 = QtWidgets.QLineEdit(addObj)
        self.lineEdit_12.textChanged.connect(self.validateFields)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.metadataLabel = QtWidgets.QLabel(addObj)
        self.metadataLabel.setObjectName("metadataLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.metadataLabel)
        self.comboBox = QtWidgets.QComboBox(addObj)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(addObj)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.setValidators(addObj)

        self.retranslateUi(addObj)

        self.oKbtn = self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok)
        self.oKbtn.setEnabled(False)
        self.buttonBox.accepted.connect(addObj.accept)
        self.buttonBox.rejected.connect(addObj.reject)
        QtCore.QMetaObject.connectSlotsByName(addObj)

    def retranslateUi(self, addObj):
        _translate = QtCore.QCoreApplication.translate
        addObj.setWindowTitle(_translate("addObj", "Dialog"))
        self.nameLabel.setText(_translate("addObj", "<font color=\"white\">Name</font> <font color=\"red\">*</font>"))
        self.timeLabel.setText(_translate("addObj", "Time"))
        self.coursseLabel.setText(_translate("addObj", "Coursse"))
        self.speedLabel.setText(_translate("addObj", "Speed"))
        self.symbolLabel.setText(_translate("addObj", "Symbol"))
        self.srccallLabel.setText(_translate("addObj", "Source call"))
        self.dstcallLabel.setText(_translate("addObj", "Destination call"))
        self.commentLabel.setText(_translate("addObj", "Comment"))
        self.pathLabel.setText(_translate("addObj", "Path"))
        self.latitudeLabel.setText(_translate("addObj", "<font color=\"white\">Latitude</font> <font color=\"red\">*</font>"))
        self.longitudeLabel.setText(_translate("addObj", "<font color=\"white\">Longitude</font> <font color=\"red\">*</font>"))
        self.elevationLabel.setText(_translate("addObj", "<font color=\"white\">Elevation</font> <font color=\"red\">*</font>"))
        self.metadataLabel.setText(_translate("addObj", "Metadata"))

    def setValidators(self, addObj):
        regName = QtCore.QRegExp('[\w]{1,10}')
        nameValidator = QtGui.QRegExpValidator(regName, self.lineEdit)
        self.lineEdit.setValidator(nameValidator)

        regSpeed = QtCore.QRegExp('[1-9][0-9]{0,2}')
        speedValidator = QtGui.QRegExpValidator(regSpeed, self.lineEdit_4)
        self.lineEdit_4.setValidator(speedValidator)

        regSymb = QtCore.QRegExp('.{2}')
        symbValidator = QtGui.QRegExpValidator(regSymb, self.lineEdit_5)
        self.lineEdit_5.setValidator(symbValidator)

        regSrc = QtCore.QRegExp("^(?=.{1,8}$)((\w)+-?(\w)+(-?(\w))*)+$")
        srcValidator = QtGui.QRegExpValidator(regSrc, self.lineEdit_6)
        self.lineEdit_6.setValidator(srcValidator)

        regDest = QtCore.QRegExp("^(?=.{1,8}$)((\w)+-?(\w)+(-?(\w))*)+$")
        destValidator = QtGui.QRegExpValidator(regDest, self.lineEdit_7)
        self.lineEdit_7.setValidator(destValidator)

        regCom = QtCore.QRegExp(".{0,150}")
        comValidator = QtGui.QRegExpValidator(regCom, self.lineEdit_8)
        self.lineEdit_8.setValidator(comValidator)

        regPath = QtCore.QRegExp('^(?=.{1,8}$)((\w)+-?(\w)+(-?(\w))*)+$')
        pathValidator = QtGui.QRegExpValidator(regPath, self.lineEdit_9)
        self.lineEdit_9.setValidator(pathValidator)

        regLat = QtCore.QRegExp('^(\+|-)?(?:90(?:(?:\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\.[0-9]{1,6})?))$')
        latValidator = QtGui.QRegExpValidator(regLat, self.lineEdit_10)
        self.lineEdit_10.setValidator(latValidator)

        regLon = QtCore.QRegExp('^(\+|-)?(?:180(?:(?:\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\.[0-9]{1,6})?))$')
        lonValidator = QtGui.QRegExpValidator(regLon, self.lineEdit_11)
        self.lineEdit_11.setValidator(lonValidator)

        regElev = QtCore.QRegExp('^[1-9]\d{1,4}(\.\d{1,4})?$')
        elevValidator = QtGui.QRegExpValidator(regElev, self.lineEdit_12)
        self.lineEdit_12.setValidator(elevValidator)

    def validateFields(self):
        if (self.lineEdit.text() and self.lineEdit_10.text() and self.lineEdit_11.text() and self.lineEdit_12.text()):
            self.oKbtn.setEnabled(True)
        else:
            self.oKbtn.setEnabled(False)


class SpinBox(QSpinBox):
    # Replaces the valueChanged signal
    newValueChanged = QtCore.pyqtSignal(int)

    def __init__(self, parent=None):
        super(SpinBox, self).__init__(parent=parent)

        print(self.isValid())

        self.valueChanged.connect(self.onValueChanged)
        self.before_value = self.value()
        self.newValueChanged.connect(self.slot)

    def onValueChanged(self, i):
        if not self.isValid(i):
            self.setValue(self.before_value)
        else:
            self.newValueChanged.emit(i)
            self.before_value = i

    def isValid(self, value):
        if (self.minimum() - value % self.singleStep()) == 0:
            return True
        return False

    def slot(self, value):
        print(value)