# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView


class Ui_RadioSondes(object):
    def setupUi(self, RadioSondes):
        RadioSondes.setObjectName("RadioSondes")
        RadioSondes.resize(828, 605)
        RadioSondes.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(RadioSondes)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget.setObjectName("tableWidget")
        #self.tableWidget.setColumnCount(0)
        #self.tableWidget.setRowCount(0)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(11)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)

        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        RadioSondes.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RadioSondes)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 21))
        self.menubar.setObjectName("menubar")
        self.menuConnect = QtWidgets.QMenu(self.menubar)
        self.menuConnect.setObjectName("menuConnect")
        RadioSondes.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RadioSondes)
        self.statusbar.setObjectName("statusbar")
        RadioSondes.setStatusBar(self.statusbar)
        self.actionNew_DB_Connection = QtWidgets.QAction(RadioSondes)
        self.actionNew_DB_Connection.setObjectName("actionNew_DB_Connection")
        self.menuConnect.addAction(self.actionNew_DB_Connection)
        self.menubar.addAction(self.menuConnect.menuAction())

        self.retranslateUi(RadioSondes)
        QtCore.QMetaObject.connectSlotsByName(RadioSondes)

    def retranslateUi(self, RadioSondes):
        _translate = QtCore.QCoreApplication.translate
        RadioSondes.setWindowTitle(_translate("RadioSondes", "Radio Sondes Tracker"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("RadioSondes", "name"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("RadioSondes", "time"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("RadioSondes", "course"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("RadioSondes", "speed"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("RadioSondes", "symbol"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("RadioSondes", "srccall"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("RadioSondes", "dstcall"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("RadioSondes", "comment"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("RadioSondes", "path"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("RadioSondes", "geometry"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("RadioSondes", "metadata"))
        self.menuConnect.setTitle(_translate("RadioSondes", "Connect"))
        self.actionNew_DB_Connection.setText(_translate("RadioSondes", "New DB Connection"))
